name: Build OpenWrt

# 触发条件：手动触发（workflow_dispatch）或在 push 到主分支时触发
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # 使用 GitHub 提供的 Ubuntu Runner 作为构建环境
    runs-on: ubuntu-latest
    env:
      FORCE_UNSAFE_CONFIGURE: 1

    steps:
      # Step 1: 检出仓库代码
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: 释放磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      # Step 2: 设置编译环境
      - name: Set up environment
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
          libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
          libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python3 \
          python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      # Step 3: 配置编译参数（此步骤可根据需要修改）
      - name: Update and install feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # Step 4: 自定义配置（可选）
      # 你可以直接替换成自己的 .config 文件，或者进行定制化配置
      - name: Configure build
        run: |
          cp ./config.example .config
          make defconfig

      # Step 5: 编译固件
      - name: Build firmware
        run: |
          make download -j$(nproc) || make download -j1 V=s
          make -j$(nproc) || make -j1 V=s

      # Step 6: 保存编译结果
      # 将编译好的固件作为 GitHub Action 的输出
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-firmware
          path: bin/targets/
